# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and deploy master

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install, build
      run: |
           yarn install
           yarn build --if-present
      env:
        FB_API_KEY: ${{ secrets.FB_API_KEY }}
        FB_AUTH_DOMAIN: ${{ secrets.FB_AUTH_DOMAIN }}
        FB_DATABASE_URL: ${{ secrets.FB_DATABASE_URL }}
        FB_PROJECT_ID: ${{ secrets.FB_PROJECT_ID }}
        FB_STORAGE_BUCKET: ${{ secrets.FB_STORAGE_BUCKET }}
        FB_MESSAGING_SENDER_ID: ${{ secrets.FB_MESSAGING_SENDER_ID }}
        FB_APP_ID: ${{ secrets.FB_APP_ID }}
        FB_MEASUREMENT_ID: ${{ secrets.FB_MEASUREMENT_ID }}
    - name: Firebase-tools install
      run: npm install -g firebase-tools
    - name: Deploy to Firebase Hosting
      run: |
        firebase deploy --only hosting,firestore --force --token $FIREBASE_TOKEN --project $PROJECT_ID
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
    - name: Set COMMIT_MESSAGE
      run: echo ::set-env name=COMMIT_MESSAGE::$(echo "${{ github.event.head_commit.message }}" | tr '\n' ' ')
    - name: Slack Notification on SUCCESS
      if: success()
      uses: tokorom/action-slack-incoming-webhook@master
      env:
        INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
        text: ビルド成功です！やったね！
        attachments: |
          [
            {
              "color": "good",
              "author_name": "${{ github.actor }}",
              "author_icon": "${{ github.event.sender.avatar_url }}",
              "fields": [
                {
                  "title": "Commit Message",
                  "value": "${{ env.COMMIT_MESSAGE }}"
                },
                {
                  "title": "GitHub Actions URL",
                  "value": "${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}"
                },
                {
                  "title": "アプリURL",
                  "value": "${{ secrets.APP_URL }}"
                }
              ]
            }
          ]
