# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and deploy master

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install, build
      run: |
           yarn install
           yarn build --if-present
      env:
        APP_apiKey: ${{ secrets.APP_apiKey }}
        APP_authDomain: ${{ secrets.APP_authDomain }}
        APP_databaseURL: ${{ secrets.APP_databaseURL }}
        APP_projectId: ${{ secrets.APP_projectId }}
        APP_storageBucket: ${{ secrets.APP_storageBucket }}
        APP_messagingSenderId: ${{ secrets.APP_messagingSenderId }}
        APP_appId: ${{ secrets.APP_appId }}
        APP_measurementId: ${{ secrets.APP_measurementId }}
    - name: Firebase-tools install
      run: npm install -g firebase-tools
    - name: Deploy to Firebase Hosting
      run: |
        firebase use dev
        firebase deploy --only hosting --token $FIREBASE_TOKEN
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
